# Generated by Django 5.0.7 on 2024-07-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogger_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='bio',
            field=models.TextField(verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='email',
            field=models.EmailField(max_length=200, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Blogger name'),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='phone',
            field=models.CharField(max_length=200, null=True, verbose_name='Blogger Biography'),
        ),
    ]
