# Generated by Django 5.0.7 on 2024-07-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogger_bio_alter_blogger_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='phone',
            field=models.CharField(max_length=200, null=True, verbose_name='Phone Number'),
        ),
    ]
